export const exchangeRates = {
  rates: {
    btc: {
      name: 'Bitcoin',
      unit: 'BTC',
      value: 1,
      type: 'crypto',
    },
    eth: {
      name: 'Ether',
      unit: 'ETH',
      value: 14.644,
      type: 'crypto',
    },
    ltc: {
      name: 'Litecoin',
      unit: 'LTC',
      value: 303.936,
      type: 'crypto',
    },
    bch: {
      name: 'Bitcoin Cash',
      unit: 'BCH',
      value: 236.237,
      type: 'crypto',
    },
    bnb: {
      name: 'Binance Coin',
      unit: 'BNB',
      value: 87.534,
      type: 'crypto',
    },
    eos: {
      name: 'EOS',
      unit: 'EOS',
      value: 30282.255,
      type: 'crypto',
    },
    xrp: {
      name: 'XRP',
      unit: 'XRP',
      value: 56689.745,
      type: 'crypto',
    },
    xlm: {
      name: 'Lumens',
      unit: 'XLM',
      value: 303411.949,
      type: 'crypto',
    },
    link: {
      name: 'Chainlink',
      unit: 'LINK',
      value: 4172.783,
      type: 'crypto',
    },
    dot: {
      name: 'Polkadot',
      unit: 'DOT',
      value: 5019.49,
      type: 'crypto',
    },
    yfi: {
      name: 'Yearn.finance',
      unit: 'YFI',
      value: 4.138,
      type: 'crypto',
    },
    usd: {
      name: 'US Dollar',
      unit: '$',
      value: 26684.753,
      type: 'fiat',
    },
    aed: {
      name: 'United Arab Emirates Dirham',
      unit: 'DH',
      value: 97991.751,
      type: 'fiat',
    },
    ars: {
      name: 'Argentine Peso',
      unit: '$',
      value: 6287307.622,
      type: 'fiat',
    },
    aud: {
      name: 'Australian Dollar',
      unit: 'A$',
      value: 40939.748,
      type: 'fiat',
    },
    bdt: {
      name: 'Bangladeshi Taka',
      unit: '৳',
      value: 2860730.981,
      type: 'fiat',
    },
    bhd: {
      name: 'Bahraini Dinar',
      unit: 'BD',
      value: 10057.003,
      type: 'fiat',
    },
    bmd: {
      name: 'Bermudian Dollar',
      unit: '$',
      value: 26684.753,
      type: 'fiat',
    },
    brl: {
      name: 'Brazil Real',
      unit: 'R$',
      value: 133268.995,
      type: 'fiat',
    },
    cad: {
      name: 'Canadian Dollar',
      unit: 'CA$',
      value: 36326.488,
      type: 'fiat',
    },
    chf: {
      name: 'Swiss Franc',
      unit: 'Fr.',
      value: 24186.153,
      type: 'fiat',
    },
    clp: {
      name: 'Chilean Peso',
      unit: 'CLP$',
      value: 21355808.136,
      type: 'fiat',
    },
    cny: {
      name: 'Chinese Yuan',
      unit: '¥',
      value: 188519.777,
      type: 'fiat',
    },
    czk: {
      name: 'Czech Koruna',
      unit: 'Kč',
      value: 589160.661,
      type: 'fiat',
    },
    dkk: {
      name: 'Danish Krone',
      unit: 'kr.',
      value: 185290.922,
      type: 'fiat',
    },
    eur: {
      name: 'Euro',
      unit: '€',
      value: 24866.187,
      type: 'fiat',
    },
    gbp: {
      name: 'British Pound Sterling',
      unit: '£',
      value: 21614.089,
      type: 'fiat',
    },
    hkd: {
      name: 'Hong Kong Dollar',
      unit: 'HK$',
      value: 208993.654,
      type: 'fiat',
    },
    huf: {
      name: 'Hungarian Forint',
      unit: 'Ft',
      value: 9238261.622,
      type: 'fiat',
    },
    idr: {
      name: 'Indonesian Rupiah',
      unit: 'Rp',
      value: 400487447.324,
      type: 'fiat',
    },
    ils: {
      name: 'Israeli New Shekel',
      unit: '₪',
      value: 99422.454,
      type: 'fiat',
    },
    inr: {
      name: 'Indian Rupee',
      unit: '₹',
      value: 2203221.193,
      type: 'fiat',
    },
    jpy: {
      name: 'Japanese Yen',
      unit: '¥',
      value: 3753343.987,
      type: 'fiat',
    },
    krw: {
      name: 'South Korean Won',
      unit: '₩',
      value: 35315403.176,
      type: 'fiat',
    },
    kwd: {
      name: 'Kuwaiti Dinar',
      unit: 'KD',
      value: 8205.294,
      type: 'fiat',
    },
    lkr: {
      name: 'Sri Lankan Rupee',
      unit: 'Rs',
      value: 8067656.142,
      type: 'fiat',
    },
    mmk: {
      name: 'Burmese Kyat',
      unit: 'K',
      value: 56030878.687,
      type: 'fiat',
    },
    mxn: {
      name: 'Mexican Peso',
      unit: 'MX$',
      value: 470449.533,
      type: 'fiat',
    },
    myr: {
      name: 'Malaysian Ringgit',
      unit: 'RM',
      value: 122776.55,
      type: 'fiat',
    },
    ngn: {
      name: 'Nigerian Naira',
      unit: '₦',
      value: 12315013.688,
      type: 'fiat',
    },
    nok: {
      name: 'Norwegian Krone',
      unit: 'kr',
      value: 295889.378,
      type: 'fiat',
    },
    nzd: {
      name: 'New Zealand Dollar',
      unit: 'NZ$',
      value: 44136.235,
      type: 'fiat',
    },
    php: {
      name: 'Philippine Peso',
      unit: '₱',
      value: 1491424.235,
      type: 'fiat',
    },
    pkr: {
      name: 'Pakistani Rupee',
      unit: '₨',
      value: 7615828.616,
      type: 'fiat',
    },
    pln: {
      name: 'Polish Zloty',
      unit: 'zł',
      value: 112701.721,
      type: 'fiat',
    },
    rub: {
      name: 'Russian Ruble',
      unit: '₽',
      value: 2137742.091,
      type: 'fiat',
    },
    sar: {
      name: 'Saudi Riyal',
      unit: 'SR',
      value: 100079.192,
      type: 'fiat',
    },
    sek: {
      name: 'Swedish Krona',
      unit: 'kr',
      value: 288539.569,
      type: 'fiat',
    },
    sgd: {
      name: 'Singapore Dollar',
      unit: 'S$',
      value: 36029.433,
      type: 'fiat',
    },
    thb: {
      name: 'Thai Baht',
      unit: '฿',
      value: 926621.977,
      type: 'fiat',
    },
    try: {
      name: 'Turkish Lira',
      unit: '₺',
      value: 532971.91,
      type: 'fiat',
    },
    twd: {
      name: 'New Taiwan Dollar',
      unit: 'NT$',
      value: 819029.798,
      type: 'fiat',
    },
    uah: {
      name: 'Ukrainian hryvnia',
      unit: '₴',
      value: 985407.528,
      type: 'fiat',
    },
    vef: {
      name: 'Venezuelan bolívar fuerte',
      unit: 'Bs.F',
      value: 2671.944,
      type: 'fiat',
    },
    vnd: {
      name: 'Vietnamese đồng',
      unit: '₫',
      value: 626558009.553,
      type: 'fiat',
    },
    zar: {
      name: 'South African Rand',
      unit: 'R',
      value: 524619.316,
      type: 'fiat',
    },
    xdr: {
      name: 'IMF Special Drawing Rights',
      unit: 'XDR',
      value: 19932.576,
      type: 'fiat',
    },
    xag: {
      name: 'Silver - Troy Ounce',
      unit: 'XAG',
      value: 1144.139,
      type: 'commodity',
    },
    xau: {
      name: 'Gold - Troy Ounce',
      unit: 'XAU',
      value: 13.708,
      type: 'commodity',
    },
    bits: {
      name: 'Bits',
      unit: 'μBTC',
      value: 1000000,
      type: 'crypto',
    },
    sats: {
      name: 'Satoshi',
      unit: 'sats',
      value: 100000000,
      type: 'crypto',
    },
  },
}
